# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-17 21:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0002_auto_20170917_1842'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '\u041a\u043e\u043c\u043c\u0435\u043d\u0442', 'verbose_name_plural': '\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u044b'},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name': '\u041b\u0430\u0439\u043a', 'verbose_name_plural': '\u041b\u0430\u0439\u043a\u0438'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': '\u041f\u043e\u0441\u0442', 'verbose_name_plural': '\u041f\u043e\u0441\u0442\u044b'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u0410\u0432\u0442\u043e\u0440'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='likes_count',
            field=models.IntegerField(default=0, verbose_name='\u0412\u0441\u0435\u0433\u043e \u043b\u0430\u0439\u043a\u043e\u0432'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='\u0442\u0435\u043a\u0441\u0442 \u043a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='like',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u0410\u0432\u0442\u043e\u0440'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u0410\u0432\u0442\u043e\u0440'),
        ),
        migrations.AlterField(
            model_name='post',
            name='comments_count',
            field=models.IntegerField(default=0, verbose_name='\u0412\u0441\u0435\u0433\u043e \u043a\u043e\u043c\u043c\u0435\u043d\u0442\u043e\u0432'),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes_count',
            field=models.IntegerField(default=0, verbose_name='\u0412\u0441\u0435\u0433\u043e \u043b\u0430\u0439\u043a\u043e\u0432'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(verbose_name='\u0442\u0435\u043a\u0441\u0442 \u043f\u043e\u0441\u0442\u0430'),
        ),
    ]
